# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-12 11:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='section',
            name='name',
            field=models.CharField(max_length=50),
        ),
    ]
